### ISSUE TITLE
no implementation found for virtual library 

### ISSUE THREAD

**Issue by mimoo** [dannywillems/ocaml-bls12-381#5]
Hello, I am getting the following error when I try running the test on a simple program:

```ocaml
module Privkey = struct
  let keygen _ = 
    let ikm = Bytes.create 32 in
    Randoml.rand_fill ikm;
    Bls12_381.Signature.generate_sk ikm
end

let%test "keygen" =
  let key = Privkey.keygen () in
  printf "%s\n" key
```

```
Error: No implementation found for virtual library "bls12-381" in
/Users/xxx/.opam/4.13.1/lib/bls12-381.
-> required by library "narwhall" in _build/default
```

**Comment by dannywillems** [comment]
If you use bls12-381 before release 3.0.0, you need to add `bls12-381-unix` in `library` if you are building an executable. From 3.0.0 there is no virtual library anymore and `bls12-381` is enough.
See https://dune.readthedocs.io/en/stable/variants.html

**Comment by mimoo** [comment]
interesting, `opam install bls12-381` installs version 1.1.0 by default :o I don't know enough about opam to understand why, perhaps it was because I didn't run `opam update` in a while?

**Comment by dannywillems** [comment]
Yes, you must run `opam update` first

**Comment by dannywillems** [comment]
I close the issue as it certainly comes from a missing `opam update`.
