### ISSUE TITLE
helping serialization

### ISSUE THREAD

**Issue by mimoo** [dannywillems/ocaml-bls12-381#6]
Hey hey,

So I have some custom records, and I want to serialize them. It seems like in OCaml the common way to do this is to use `[@@deriving sexp]`, but this won't work with the types that are in Bls12-381. Would it make sense to add this (or add the specific functions it derives manually) within the library itself here?

**Comment by dannywillems** [comment]
I would prefer keeping the library dependencies as small as possible. Also, it is not the "common way" to use sexp, it depends the type of serialisation you want. In the library, there are bytes (de)serialisers.

**Comment by mimoo** [comment]
Ah yeah I think I was misled by the real world of ocaml book :P I have been using the to_bytes function to do that, thanks a lot! (sorry for the noob questions ^^)
